version: '3.9'
services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: virtual-stock-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
