name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: FRONTEND/package-lock.json

      - name: Install dependencies
        working-directory: FRONTEND
        run: npm ci --legacy-peer-deps

      - name: Lint
        working-directory: FRONTEND
        run: npm run lint --if-present

      - name: Test
        working-directory: FRONTEND
        run: npm test --if-present

      - name: Build
        working-directory: FRONTEND
        env:
          VITE_BASE_PATH: '/${{ github.event.repository.name }}/'
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: FRONTEND/dist
          if-no-files-found: error


