name: pages build and deployment (disabled)

on:
  push:
    branches: [ never-run-this-branch ]
  workflow_dispatch: # keep manual trigger but do nothing

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub Pages workflow disabled in favor of AWS Amplify Hosting"


